---
title: "Untitled"
author: "Sam Parsons"
date: "1 February 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("bootnet")
library("foreign")
library("tidyverse")
```


```{r}

```

```{r load required data sets}
demographics <- read.spss("alternative/BMI_Demographics_Wave1.sav", to.data.frame = TRUE)
scores1 <- read.spss("alternative/1) SESSIONONEMASTERFILE_afternewSyntax_CASEchanges_missingdatachanges.sav", to.data.frame = TRUE)
scores2 <- read.spss("alternative/2) SESSIONTWOMASTERFILE_afterSyntax_missingdata.sav", to.data.frame = TRUE)
Dot_Probe <- read.spss("alternative/1) New Dot-probe Mastefile_3SD_peremotion_4ppsdeleted_moodscales.sav", to.data.frame = TRUE)
AIBQ <- read.spss("alternative/Complete_AIBQ_allPPs.sav", to.data.frame = TRUE)
Memory <- read.spss("alternative/2) Complete_SRET_Masterfile.sav", to.data.frame = TRUE)


```



```{r create dataframe for analysis}
# first extract the variables of interest

Qdat <- data.frame(subject = scores2$Master_subject,
                   MHC_Emo = scores2$MCSHC_Emotional_wellbeing,
                   MHC_Soc = scores2$MCSHC_Social_wellbeing,
                   MHC_Psy = scores2$MCSHC_Psychological_wellbeing,
                   MHC_Tot = scores2$MCSHC_Total
 )

DPdat <- data.frame(subject  = Dot_Probe$Master_subject,
                    DP_angry = Dot_Probe$angrybias,
                    DP_happy = Dot_Probe$happybias,
                    DP_pain  = Dot_Probe$painbias)
AIBQdat <- data.frame(subject = AIBQ$Master_subject,
                      Pos_Soc    = AIBQ$Interpretation_Pos_Social,
                      Pos_nonsoc = AIBQ$Interpretation_Pos_Nonsocial,
                      Neg_soc    = AIBQ$Interpretation_Neg_Social,
                      Neg_nonsoc = AIBQ$Interpretation_Neg_Nonsocial)
Memdat <- data.frame(subject = Memory$Master_subject,
                     MEM_pos = Memory$PosEndorsedAndRecalled,
                     MEM_neg = Memory$NegEndorsedAndRecalled)

# combine into one dataframe
CCBH <- cbind(Qdat,DPdat,AIBQdat,Memdat)


# remove previous data frames to save space
remove(list = c("scores1","Dot_Probe", "AIBQ", "Memory", "Qdat", "DPdat", "AIBQdat", "Memdat"))


# remove participants with incomplete data # n=443 (with that extra participant, and DPT acc < 70% removed)
CCBH <- na.omit(CCBH)
CCBH <- subset(CCBH, CCBH$subject != "301041")
CCBH <- subset(CCBH, CCBH$subject != "381491" & CCBH$subject != "331126" & CCBH$subject != "311002" & CCBH$subject != "311019") # removing participants with < 70% accuracy on task
CCBH <-   CCBH %>% 
                filter(subject != 311002,
                       subject != 311019,
                       subject != 311028,
                       subject != 301036,
                       subject != 301041,
                       subject != 331126,
                       subject != 381491,
                       subject != 381441,
                       subject != 381442,
                       subject != 381443,
                       subject != 381444,
                       subject != 381478 )  # removing participants with missing or incorrectly logged DPT data



mean(CCBH$MHC_Tot)
sd(CCBH$MHC_Tot)
quantile(CCBH$MHC_Tot, c(.33, .66)) # 37 and 47

```



```{r create high and low groups}
CCBH_sortbyMHC <- arrange(CCBH, MHC_Tot)

# checking sample size for the tertile split
low  <- sum(CCBH_sortbyMHC$MHC_Tot < 37) # 145
mid  <- sum(CCBH_sortbyMHC$MHC_Tot >= 37 & CCBH_sortbyMHC$MHC_Tot <= 47) # 153
high <- sum(CCBH_sortbyMHC$MHC_Tot > 47) # 150

# subsetting into three samples
low2 <- subset(CCBH_sortbyMHC, MHC_Tot < 37) # 
mid2 <- subset(CCBH_sortbyMHC, MHC_Tot >= 37 & MHC_Tot <= 47)
high2 <- subset(CCBH_sortbyMHC, MHC_Tot > 47)

low_ppt <- unique(low2$subject)
mid_ppt <- unique(mid2$subject)
high_ppt <- unique(high2$subject)


# selecting only the variables for inclusion in the networks
low3  <- low2[,c(7,8,9,11,12,13,14,16,17)]
mid3  <- mid2[,c(7,8,9,11,12,13,14,16,17)]
high3 <- high2[,c(7,8,9,11,12,13,14,16,17)]

# changing variable names for interpretability
variable_names  <- c("AB_Ang", "AB_Hap", "AB_Pain" ,"IB_S_Pos", "IB_N_Pos", "IB_S_Neg", "IB_N_Neg", "MB_Pos", "MB_Neg")
colnames(low3)  <- variable_names
colnames(mid3)  <- variable_names
colnames(high3) <- variable_names

```


```{r}
low3$MH <- 0
high3$MH <- 1

full <- rbind(low3, high3)


library("mgm")


fit_obj <- mgm(data = full,
  type = c(rep("g", 9), "c"),
  level = c(rep(1, 9), 2),
  ruleReg = "OR",
  k = 2,
  binarySign = TRUE)



p_obj <- predict(fit_obj, full,
errorCat = c("CC","nCC","CCmarg"),
errorCon = c("R2"))


error_list <- list() # List for ring-segments
for(i in 1:9) error_list[[i]] <- p_obj$errors[i,2]
beyondmarg <- p_obj$errors[10,3]-p_obj$errors[10,5]
error_list[[10]] <- c(p_obj$errors[10,5],beyondmarg)

color_list <- list() # List for Colors
for(i in 1:9) color_list[[i]] <- "#90B4D4"
color_list[[10]] <- c("#ffa500", "#ff4300")

library(qgraph)
qgraph(fit_obj$pairwise$wadj, pie = error_list,
  layout="spring", labels = colnames(full),
  pieColor = color_list, label.cex = .9,
  edge.color = fit_obj$pairwise$edgecolor,
  curveAll = TRUE, curveDefault = .6,
  cut = 0, labels = col(full))




boot1 <- estimateNetwork(data = full,
                 default = "mgm",
                  type = c(rep("g", 9), "c"),
                  level = c(rep(1, 9), 2),
                  rule = "OR",
                  binarySign = TRUE,
                  moderators = c(10),
                  criterion = "CV")

plot(boot1)

boot2 <- bootnet(boot1, nBoots = 50, nCores = 4)

plot(boot2, order = "sample")



```


```{r}

fit_obj2 <- mgm(data = full,
  type = c(rep("g", 9), "c"),
  level = c(rep(1, 9), 2),
  ruleReg = "OR",
  k = 2,
  binarySign = TRUE,
  moderators = c(10)#,
 # lambdaSel = "EBIC",
  #lambdaGam = .5
)

p_obj2 <- predict(fit_obj2, full,
errorCat = c("CC","nCC","CCmarg"),
errorCon = c("R2"))


error_list <- list() # List for ring-segments
for(i in 1:9) error_list[[i]] <- p_obj2$errors[i,2]
beyondmarg <- p_obj2$errors[10,3]-p_obj2$errors[10,5]
error_list[[10]] <- c(p_obj2$errors[10,5],beyondmarg)

color_list <- list() # List for Colors
for(i in 1:9) color_list[[i]] <- "#90B4D4"
color_list[[10]] <- c("#ffa500", "#ff4300")

#library(qgraph)
qgraph(fit_obj2$pairwise$wadj, pie = error_list,
  layout="spring", labels = colnames(full),
  pieColor = color_list, label.cex = .9,
  edge.color = fit_obj2$pairwise$edgecolor,
  curveAll = TRUE, curveDefault = .6,
  cut = 0, labels = col(full))


FactorGraph(object = fit_obj2,
edge.labels = FALSE,
PairwiseAsEdge = TRUE,
labels = colnames(full))


img <- FactorGraph(object = fit_obj2,
edge.labels = FALSE,
PairwiseAsEdge = TRUE,
labels = colnames(full),
pie = c(error_list, rep(0,7)),
pieBorder = c(rep(.2,10),rep(0,7)),
pieColor = c(color_list,rep(0,7)),
vsize = 2,
vsize2 = .5,
label.cex = 1)



FactorGraph(object = boot1,
edge.labels = FALSE,
PairwiseAsEdge = TRUE)



bootnet(fit_obj2, nBoots = 100)

```




